services:
  catalogue:
    build: ./catalogue
    image: kanishk244/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./USER
    image: kanishk244/user:1.0.0
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./CART
    image: kanishk244/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: kanishk244/shipping:1.0.0
    container_name: shipping
    depends_on:
    - cart
    - mysql
  payment:
    build: ./payment
    image: kanishk244/payment:1.0.0
    container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq

  frontend:
    build: ./frontend
    image: kanishk244/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  mongodb:
    build: ./mongodb
    image: kanishk244/mongodb:1.0.0
    container_name: mongodb
    volumes:
      - /data/db

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  mysql:
    build: ./MYSQL
    image: kanishk244/mysql:1.0.0
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if yes we need to create the network manually
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: