services:
  catalogue:
    build: ./catalogue
    image: kanishk244/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: kanishk244/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    build: ./mongodb
    image: kanishk244/mongodb:1.0.0
    container_name: mongodb
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if yes we need to create the network manually